apiVersion: skaffold/v4beta5
kind: Config

build:
  local:
      push: true
  artifacts:
  - image: about
    ko:
      dependencies:
        paths:
          - cmd/about/**
          - internal/**
      main: ./cmd/about
deploy:
  # kubeContext: kind-kind
  helm:
    releases:
    - name: about
      chartPath: charts/about
      setValueTemplates:
        image.repository: "{{.IMAGE_REPO_about}}"
        image.tag: "{{.IMAGE_TAG_about}}"

profiles:
  - name: dev
    activation:
      - command: dev
  - name: kind
    activation:
      - kubeContext: kind-kind
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          aceContext.aceEnvVersion: "1.2.3"
          aceContext.domain: about.127.0.0.1.nip.io 
          aceContext.domainExternal: about.external.127.0.0.1.nip.io
          aceContext.storageClass.db: standard
          
          ingress.enabled: true
          ingress.hosts:
          - host: about.127.0.0.1.nip.io
            paths:
            - path: /
              pathType: ImplementationSpecific




